import { ClerkProvider } from "@clerk/nextjs/app-beta";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body>
          <main className="flex min-h-screen flex-col items-center bg-black text-white">
            {children}
          </main>
        </body>
      </ClerkProvider>
    </html>
  );
}
